name: hi_toeic
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ui
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3

  # state management
  get: ^4.6.6

  #api
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  collection: ^1.18.0
  expandable: ^5.0.1
  path: ^1.9.0
  photo_view: ^0.15.0
  http: ^1.2.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  lottie: ^3.1.3
  shared_preferences: ^2.3.2
  swipe_refresh: ^1.1.2
  freezed_annotation: ^2.4.4
  flutter_svg: ^2.0.10+1
  flutter_local_notifications: ^17.2.3
  flutter_dotenv: ^5.2.1
  salomon_bottom_bar: ^3.3.2
  font_awesome_flutter: ^10.7.0
  supabase: ^2.5.0
  expandable_text: ^2.3.0
  supabase_flutter: ^2.8.0
  loading_animation_widget: ^1.3.0
  wave_linear_progress_indicator: ^0.1.0
  flutter_card_swiper: ^7.0.2
  flutter_flip_card: ^0.0.6
  translator_plus: ^1.0.1
  just_audio: ^0.9.41
  autocorrect_and_autocomplete_engine: ^0.0.2
  flutter_typeahead: ^5.2.0
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  floating_action_bubble: ^1.1.4
  numberpicker: ^2.1.2
  get_it: ^8.0.0
  flutter_tts: ^4.0.2
  youtube_explode_dart: ^2.3.2
  youtube_player_flutter: ^9.1.1
  youtube_caption_scraper: ^0.2.0
  dio: ^5.7.0
  scrollable_positioned_list: ^0.3.8
  flutter_launcher_icons: ^0.14.1
  webview_flutter: ^4.10.0
  zego_uikit_signaling_plugin: ^2.8.6
  zego_uikit_prebuilt_live_streaming: ^3.13.5
  either_dart: ^1.0.0
  google_sign_in: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  table_calendar: ^3.1.2
  isitaword: ^0.0.4
  firebase_remote_config: ^5.1.3
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # lint rules
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

get_cli:
  sub_folder: false

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/png/
    - assets/images/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope-ExtraBold.ttf
        - asset: assets/fonts/Manrope-ExtraLight.ttf
        - asset: assets/fonts/Manrope-Light.ttf
        - asset: assets/fonts/Manrope-Medium.ttf
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
